new

diff --git a/modules/install-unbound/install-unbound b/modules/install-unbound/install-unbound
--- a/modules/install-unbound/install-unbound
+++ b/modules/install-unbound/install-unbound
@@ -3,63 +3,83 @@
 # install-unbound - Install and configure unbound for usage on a wireguard server
 # 
 
-set -e
-
 function print_usage {
-  echo
-  echo "Usage: install-unbound [OPTIONS]"
-  echo
-  echo "This script can be used to install unbound in a simple configuration."
-  echo
-  echo "Options:"
-  echo
-  echo -e "  --domain\t\tThe name that will be the local domain."
-  echo -e "  --threads\t\tThe number of cores the machine has. Defaults to 1."
-  echo
-  echo "Example:"
-  echo
-  echo "  install-unbound --domain test.local"
+        echo
+        echo "Usage: install-unbound [OPTIONS]"
+        echo
+        echo "This script can be used to install unbound in a simple configuration."
+        echo
+        echo "Options:"
+        echo
+        echo -e "  --domain\t\tThe name that will be the local domain."
+        echo -e "  --threads\t\tThe number of cores the machine has. Defaults to 1."
+        echo -e "  --subnet\t\tThe CIDR Block for the managed subnet."
+        echo
+        echo "Example:"
+        echo
+        echo "  install-unbound --domain test.local"
 }
 
 
 function log {
-  local -r level="$1"
-  local -r message="$2"
-  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
+        local -r level="$1"
+        local -r message="$2"
+        local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+        >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
 }
 
 function log_info {
-  local -r message="$1"
-  log "INFO" "$message"
+        local -r message="$1"
+        log "INFO" "$message"
 }
 
 function log_warn {
-  local -r message="$1"
-  log "WARN" "$message"
+        local -r message="$1"
+        log "WARN" "$message"
 }
 
 function log_error {
-  local -r message="$1"
-  log "ERROR" "$message"
+        local -r message="$1"
+        log "ERROR" "$message"
 }
 
 function assert_not_empty {
-  local -r arg_name="$1"
-  local -r arg_value="$2"
+        local -r arg_name="$1"
+        local -r arg_value="$2"
 
-  if [[ -z "$arg_value" ]]; then
-    log_error "The value for '$arg_name' cannot be empty"
-    print_usage
-    exit 1
-  fi
+        if [[ -z "$arg_value" ]]; then
+            log_error "The value for '$arg_name' cannot be empty"
+            print_usage
+            exit 1
+        fi
 }
+
+function replace_or_insert {
+        local -r line="$1"
+        local -r expression=`echo $line | awk -F '=' '{print $1}' | tr -d ' '`
+        local -r file="$2"
+        
+        grep -q $expression $file
+        if [[ $? -ne 0 ]] ; then
+            echo $line >> $file
+        else
+            sed -i -e "s/^.*$expression.*$/$line/" $file
+        fi
+}
+
+function increase_rmem_wmem {
+        replace_or_insert "net.core.rmem_max = 2097152" /etc/sysctl.conf
+        replace_or_insert "net.core.wmem_max = 2097152" /etc/sysctl.conf
+        sysctl -p
+}
+
 
 function install_unbound {
         apt-get -y update
         apt install -y unbound
         mkdir -p /var/lib/unbound
         wget https://www.internic.net/domain/named.root -O /var/lib/unbound/root.hints
+        chown unbound:unbound /var/lib/unbound/root.hints
 }
 
 function disable_systemd_resolved {
@@ -72,10 +92,19 @@ systemd-resolved=false
 EOF
 }
 
+
+function allow_port_53 {
+        local -r subnet="$1"
+        ufw allow from $subnet to any port 53 proto tcp
+        ufw allow from $subnet to any port 53 proto udp
+        ufw reload        
+}
+
 function create_unbound_conf {
         domain=$1
         threads=$2
         slabs=$((2 * $threads))
+        subnet=$3
 
         cat << EOF > /etc/unbound/unbound.conf
 ## Authoritative, validating, recursive caching DNS
@@ -88,9 +117,7 @@ server:
     do-ip6: no
     do-udp: yes
     do-tcp: yes
-    access-control: 10.0.0.0/8 allow
-    access-control: 127.0.0.0/8 allow
-    access-control: 192.168.0.0/16 allow
+    access-control: $subnet allow
     root-hints: "/var/lib/unbound/root.hints"
     hide-identity: yes
     hide-version: yes
@@ -108,27 +135,26 @@ server:
     rrset-cache-size: 128m
     msg-cache-size: 128m
     so-rcvbuf: 1m
-    private-address: 192.168.0.0/16
-    private-address: 172.16.0.0/12
-    private-address: 10.0.0.0/8
-    private-domain: "$domain"
+    private-address: $subnet
+    private-domain: $domain
     unwanted-reply-threshold: 10000
     do-not-query-localhost: no
-    auto-trust-anchor-file: "/var/lib/unbound/root.key"
     val-clean-additional: yes
-		qname-minimisation: yes
     local-zone: "$domain." static
   forward-zone:
    name: "."
    forward-addr: 213.133.98.98@53
    forward-addr: 213.133.99.99@53
-   forward-addr: 213.133.100.100@53
+   forward-addr: 213.133.100.100@53 
+
+include: "/etc/unbound/unbound.conf.d/*.conf" 
 EOF
 }
 
 function install {
   local domain="nodomain"
   local threads="1"
+  local subnet="10.0.0.0/8"
 
   while [[ $# -gt 0 ]]; do
     local key="$1"
@@ -144,6 +170,11 @@ function install {
         threads="$2"
         shift
         ;;
+      --subnet)
+        assert_not_empty "$key" "$2"
+        subnet="$2"
+        shift
+        ;;
       *)
         log_error "Unrecognized argument: $key"
         print_usage
@@ -156,9 +187,11 @@ function install {
 
   log_info "Starting Unbound install"
 
+  increase_rmem_wmem
   install_unbound
   disable_systemd_resolved
-  create_unbound_conf $domain $threads
+  create_unbound_conf $domain $threads $subnet
+  allow_port_53 $subnet
 
   if command -v unbound; then
     log_info "unbound install complete!";
diff --git a/modules/install-wireguard/install-wireguard b/modules/install-wireguard/install-wireguard
--- a/modules/install-wireguard/install-wireguard
+++ b/modules/install-wireguard/install-wireguard
@@ -1,10 +1,113 @@
 #!/bin/bash
 
-echo "installing wireguard $1 ..."
-while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done
+function print_usage {
+        echo
+        echo "Usage: install-wireguard [OPTIONS]"
+        echo
+        echo "This script can be used to install wireguard in a simple configuration."
+        echo
+        echo "Options:"
+        echo
+        echo -e "  --subnet\t\tThe CIDR Block for the managed subnet. Defaults to 10.0.0.0/8"
+        echo
+        echo "Example:"
+        echo
+        echo "  install-wireguard --subnet 192.168.0.0/16"
+}
 
-apt-get -y update
-apt-get -y install wireguard
-ufw allow 51820/udp
-ufw reload
-apt -y install resolvconf
+
+function log {
+        local -r level="$1"
+        local -r message="$2"
+        local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+        >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
+}
+
+function log_info {
+        local -r message="$1"
+        log "INFO" "$message"
+}
+
+function log_warn {
+        local -r message="$1"
+        log "WARN" "$message"
+}
+
+function log_error {
+        local -r message="$1"
+        log "ERROR" "$message"
+}
+
+function assert_not_empty {
+        local -r arg_name="$1"
+        local -r arg_value="$2"
+
+        if [[ -z "$arg_value" ]]; then
+            log_error "The value for '$arg_name' cannot be empty"
+            print_usage
+            exit 1
+        fi
+}
+
+
+
+
+function allow_port_51820 {
+            local -r subnet="$1"
+            ufw allow from $subnet to any port 53 proto tcp
+            ufw allow from $subnet to any port 53 proto udp
+            ufw reload        
+}
+
+function install_wireguard {
+            apt-get -y update > /dev/null
+            apt-get -y install wireguard
+}
+
+function install_resolvconf {
+            # install for DNS function in wg-quick
+            apt -y install resolvconf
+}
+
+
+
+function install {
+            local domain="nodomain"
+            local threads="1"
+            local subnet="10.0.0.0/8"
+
+            while [[ $# -gt 0 ]]; do
+            local key="$1"
+
+            case "$key" in
+                --subnet)
+                assert_not_empty "$key" "$2"
+                subnet="$2"
+                shift
+                ;;
+                *)
+                log_error "Unrecognized argument: $key"
+                print_usage
+                exit 1
+                ;;
+            esac
+
+            shift
+            done
+
+            log_info "Starting Wireguard install"
+
+            install_wireguard
+            install_resolvconf
+            allow_port_51820 $subnet
+
+            if command -v wg; then
+                    log_info "Wireguard install complete!";
+            else
+                    log_info "Could not find wg command. Aborting.";
+            exit 1;
+            fi
+}
+
+while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done
+install "$@"
